Repository organization/youtube-music-next, pull requests merged in 2023-10, with the labels that each got.

#20 feat: apply rollup 🚀
  .eslintignore
  .github/workflows/build.yml
  index.ts
  menu.ts
  package-lock.json
  package.json
  plugins/adblocker/blocker.ts
  plugins/adblocker/inject-cliqz-preload.ts
  plugins/album-color-theme/back.ts
  plugins/blur-nav-bar/back.ts
  plugins/captions-selector/front.ts
  plugins/downloader/back.ts
  plugins/downloader/front.ts
  plugins/in-app-menu/back.ts
  plugins/in-app-menu/front.ts
  plugins/lyrics-genius/back.ts
  plugins/navigation/back.ts
  plugins/navigation/front.ts
  plugins/no-google-login/back.ts
  plugins/notifications/interactive.ts
  plugins/notifications/utils.ts
  plugins/picture-in-picture/back.ts
  plugins/picture-in-picture/front.ts
  plugins/playback-speed/front.ts
  plugins/precise-volume/back.ts
  plugins/quality-changer/front.ts
  plugins/utils.ts
  plugins/video-toggle/back.ts
  plugins/video-toggle/front.ts
  plugins/visualizer/back.ts
  plugins/visualizer/front.ts
  plugins/visualizer/menu.ts
  plugins/visualizer/visualizers/butterchurn.ts
  plugins/visualizer/visualizers/index.ts
  plugins/visualizer/visualizers/visualizer.ts
  plugins/visualizer/visualizers/vudio.ts
  plugins/visualizer/visualizers/wave.ts
  rollup.main.config.ts
  rollup.preload.config.ts
  tests/index.test.mjs
  tsconfig.json
  youtube-music.d.ts
Labels: enhancement

#33 feat(ambient-mode): add ambient mode plugin
  config/defaults.ts
  index.ts
  plugins/ambient-mode/back.ts
  plugins/ambient-mode/front.ts
  plugins/ambient-mode/style.css
  preload.ts
Labels: enhancement, plugin

#35 feat: use fast-average-color instead of fast-average-color-node
  package-lock.json
  package.json
  plugins/album-color-theme/back.ts
  plugins/album-color-theme/front.ts
  rollup.main.config.ts
  rollup.preload.config.ts
Labels: bug, Type: Dependency

#36 chore(docs): versioning
  VERSIONING.md
Labels: documentation
